server:
  port: 9000

spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        service-labels:
          spring-boot: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
